services:
  - type: web
    name: asy-global-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        fromService:
          name: asy-global-portal
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: STORAGE_DIR
        value: ./storage

  - type: web
    name: asy-global-portal
    runtime: static
    rootDir: client
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: dist
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: 'true'
      - key: VITE_API_URL
        fromService:
          name: asy-global-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

