import { useEffect, useState } from 'react';
import { CheckCircle2, Edit3, HeartHandshake, Plus, Quote, Star, Trash2 } from 'lucide-react';
import { api } from '../services/api';

const blank={client_name:'',destination:'',service_type:'',quote:'',consent_for_marketing:false,featured:false,is_published:false};

export default function Testimonials(){
 const [items,setItems]=useState([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null); const [show,setShow]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 async function load(){try{const{data}=await api.get('/testimonials');setItems(data.testimonials||[]);setError('')}catch(err){setError(err.response?.data?.message||'Could not load testimonials.')}}
 useEffect(()=>{load()},[]);
 function openCreate(){setEditing(null);setForm(blank);setShow(true)} function openEdit(item){setEditing(item);setForm({...item,consent_for_marketing:Boolean(item.consent_for_marketing),featured:Boolean(item.featured),is_published:Boolean(item.is_published)});setShow(true)} function close(){setShow(false);setEditing(null);setForm(blank)}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const payload={...form};if(!payload.consent_for_marketing)payload.is_published=false;if(editing)await api.patch(`/testimonials/${editing.id}`,payload);else await api.post('/testimonials',payload);close();await load()}catch(err){setError(err.response?.data?.message||'Could not save testimonial.')}finally{setSaving(false)}}
 async function remove(item){if(!window.confirm(`Delete testimonial from ${item.client_name}?`))return;try{await api.delete(`/testimonials/${item.id}`);await load()}catch(err){setError(err.response?.data?.message||'Could not delete testimonial.')}}
 return <div>
  <div className="page-heading"><div><span className="eyebrow">CLIENT STORIES</span><h2>Testimonials</h2><p>A dedicated library for real client experiences. Publishing is enabled only when marketing consent is recorded.</p></div><button className="primary-btn" onClick={openCreate}><Plus size={17}/> Add testimonial</button></div>
  {error&&<div className="error-box">{error}</div>}
  <div className="testimonial-banner"><div className="testimonial-banner-icon"><HeartHandshake size={20}/></div><div><strong>Real stories build real trust.</strong><p>Store testimonials here first; later the approved stories can feed the public ASY website and social-media campaigns.</p></div><div className="testimonial-count"><strong>{items.filter(i=>i.is_published).length}</strong><span>published</span></div></div>
  <div className="testimonial-grid">
   {items.map(item=><article className="testimonial-card" key={item.id}><div className="quote-mark"><Quote size={20}/></div><div className="stars">{[1,2,3,4,5].map(n=><Star key={n} size={13} fill="currentColor"/>)}</div><blockquote>“{item.quote}”</blockquote><div className="testimonial-person"><div className="testimonial-avatar">{item.client_name.slice(0,1).toUpperCase()}</div><div><strong>{item.client_name}</strong><span>{[item.destination,item.service_type].filter(Boolean).join(' • ')||'ASY client'}</span></div></div><div className="testimonial-meta"><span className={item.is_published?'published-badge':'draft-badge'}>{item.is_published?<><CheckCircle2 size={12}/> Published</>:<>Draft</>}</span><span>{item.consent_for_marketing?'Marketing consent ✓':'Internal only'}</span></div><div className="opportunity-actions"><button className="secondary-btn compact" onClick={()=>openEdit(item)}><Edit3 size={15}/> Edit</button><button className="icon-btn danger-icon" onClick={()=>remove(item)}><Trash2 size={16}/></button></div></article>)}
   {!items.length&&<div className="empty-state-card"><HeartHandshake size={28}/><h3>No client stories yet</h3><p>Add the first genuine client experience. Keep the wording honest and only publish it when the client has agreed to marketing use.</p><button className="primary-btn" onClick={openCreate}><Plus size={16}/> Add first testimonial</button></div>}
  </div>
  {show&&<div className="modal-backdrop"><div className="modal large"><div className="modal-head"><div><span className="eyebrow">CLIENT STORY</span><h3>{editing?'Update testimonial':'Add testimonial'}</h3></div><button className="icon-btn" onClick={close}>×</button></div><form onSubmit={save} className="form-grid"><label>Client name<input required value={form.client_name} onChange={e=>setForm({...form,client_name:e.target.value})} placeholder="Client name"/></label><label>Destination<input value={form.destination||''} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="Saudi Arabia"/></label><label>Service type<input value={form.service_type||''} onChange={e=>setForm({...form,service_type:e.target.value})} placeholder="Employment / Travel / Tour"/></label><label className="span-2">Testimonial<textarea required rows="6" value={form.quote} onChange={e=>setForm({...form,quote:e.target.value})} placeholder="Write the client's actual words or a faithful approved statement…"/></label><label className="check-control span-2"><input type="checkbox" checked={Boolean(form.consent_for_marketing)} onChange={e=>setForm({...form,consent_for_marketing:e.target.checked})}/><span>The client has explicitly agreed that this testimonial may be used for ASY marketing.</span></label><label className="check-control span-2"><input type="checkbox" checked={Boolean(form.is_published)} disabled={!form.consent_for_marketing} onChange={e=>setForm({...form,is_published:e.target.checked})}/><span>Publish this testimonial (requires marketing consent).</span></label><label className="check-control span-2"><input type="checkbox" checked={Boolean(form.featured)} onChange={e=>setForm({...form,featured:e.target.checked})}/><span>Feature this story in the testimonial library.</span></label><div className="modal-actions span-2"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add testimonial'}</button></div></form></div></div>}
 </div>
}
