import { useEffect, useState } from 'react';
import { Plus, UserCog } from 'lucide-react';
import { api } from '../services/api';

export default function Users({ user }) {
  const [users,setUsers]=useState([]); const [form,setForm]=useState({full_name:'',email:'',password:'',role:'staff'}); const [show,setShow]=useState(false); const [error,setError]=useState('');
  async function load(){ const {data}=await api.get('/users'); setUsers(data.users); }
  useEffect(()=>{load().catch(()=>setError('Unable to load users.'));},[]);
  if (!['super_admin','admin'].includes(user.role)) return <div className="empty-state">You do not have permission to manage users.</div>;
  async function create(e){e.preventDefault();try{await api.post('/users',form);setForm({full_name:'',email:'',password:'',role:'staff'});setShow(false);await load();}catch(err){setError(err.response?.data?.message||'Could not create user.');}}
  async function toggle(u){await api.patch(`/users/${u.id}/status`,{is_active:!u.is_active});await load();}
  return <div><div className="page-heading"><div><span className="eyebrow">ACCESS CONTROL</span><h2>Staff & users</h2><p>Create individual accounts instead of sharing passwords.</p></div><button className="primary-btn" onClick={()=>setShow(true)}><Plus size={17}/> New user</button></div>{error&&<div className="error-box">{error}</div>}<div className="table-card"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><span className="table-primary"><span className="table-avatar"><UserCog size={16}/></span><span><strong>{u.full_name}</strong><small>ID {u.id}</small></span></span></td><td>{u.email}</td><td><span className="role-badge">{u.role.replace('_',' ')}</span></td><td><span className={u.is_active?'status-badge':'status-badge muted-badge'}>{u.is_active?'Active':'Inactive'}</span></td><td><button className="secondary-btn small" onClick={()=>toggle(u)}>{u.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div>{show&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">NEW USER</span><h3>Create account</h3></div><button className="icon-btn" onClick={()=>setShow(false)}>×</button></div><form className="form-stack" onSubmit={create}><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Temporary password<input type="password" required minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="staff">Staff</option><option value="admin">Admin</option>{user.role==='super_admin'&&<option value="super_admin">Super Admin</option>}</select></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setShow(false)}>Cancel</button><button className="primary-btn">Create user</button></div></form></div></div>}</div>;
}
